// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	http "net/http"
	client "covid/src/pkg/utils/client"

	mock "github.com/stretchr/testify/mock"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// Request provides a mock function with given fields: options
func (_m *UseCase) Request(options client.HttpOptions) (*http.Response, error) {
	ret := _m.Called(options)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(client.HttpOptions) *http.Response); ok {
		r0 = rf(options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(client.HttpOptions) error); ok {
		r1 = rf(options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
