// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	client "covid/src/pkg/utils/client"
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// Request provides a mock function with given fields: options
func (_m *UseCase) Request(options client.HttpOptions) (*http.Response, error) {
	ret := _m.Called(options)

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(client.HttpOptions) (*http.Response, error)); ok {
		return rf(options)
	}
	if rf, ok := ret.Get(0).(func(client.HttpOptions) *http.Response); ok {
		r0 = rf(options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(client.HttpOptions) error); ok {
		r1 = rf(options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
